---
- include: virtual_env.yml

-   name: Setup git
    template: src=.gitconfig dest=~/.gitconfig

-   name: Setup vim
    template: src=.vimrc dest=~/.vimrc

-   name: Setup bash
    template: src=.bashrc dest=~/.bashrc

-   name: Install pip packages
    pip: name={{ item }}
    with_items: pip_packages

-   name: Install ack
    shell: curl http://beyondgrep.com/ack-1.96-single-file > {{ basedir }}/env/bin/ack creates={{ basedir }}/env/bin/ack
-   command: chmod 0755 {{ basedir }}/env/bin/ack
